apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-demo-kolesnichenko-com-tls
spec:
  secretName: k8s-demo-kolesnichenko-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-demo.kolesnichenko.com
  dnsNames:
    - k8s-demo.kolesnichenko.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-demo.kolesnichenko.com